### ISSUE TITLE
Auto-Refresh not fully appearing on Mobile Devices

### ISSUE THREAD

**Issue by reve0716** [Chicago/opengrid#250]
Auto refresh is partially appearing on mobile device (IPhone 5C, 6S).  When creating a search and adding auto refresh on a mobile device the screen stops directly after the auto refresh function has been selected hiding the option out to change the refresh in seconds.  When flipped horizontally or vertically is the same results, partially appearing. See Images below:

![auto2](https://cloud.githubusercontent.com/assets/12734080/19092657/443b19d4-8a4d-11e6-9302-7b94b7f2c44d.png)

![auto1](https://cloud.githubusercontent.com/assets/12734080/19092655/41f3fb8c-8a4d-11e6-9c3c-871a9fa679af.png)

**Comment by PriyaDoIT** [comment]
same issue as #249

**Comment by PriyaDoIT** [comment]
fixed

**Comment by reve0716** [comment]
On the iPhone 6s and 5c the issue remains but there is a work around by having the phone vertical and collapsing each section that's expanded. 

An example would be:

Create a search - Expand Add a Dataset (Select Dataset)
Optional - Expand Add Location Preference (Select Location)
In order to see the entire auto-refresh... collapse each section (Select Data, Select Location, Existing Queries) the entire auto-refresh displays.
